baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Daan Willems'
theme = 'no-style-please'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
